blank_issues_enabled: false
contact_links:
  - name: Nexlify Discussions
    url: https://github.com/karanbagle/Nexlify/discussions
    about: Ask questions or share ideas in our community discussions.
  - name: Nexlify Documentation
    url: https://github.com/karanbagle/Nexlify/wiki
    about: Check our wiki for setup and usage guides.
